package doboard.common.cache;

import doboard.auth.User;
import doboard.auth.UserDAO;
import doboard.chores.Chore;
import doboard.chores.ChoreDAO;
import doboard.chores.ChoreService;
import doboard.dorm.Dorm;
import doboard.dorm.DormDAO;
import doboard.dorm.DormMember;
import doboard.expenses.Bill;
import doboard.expenses.BillDAO;
import doboard.expenses.BillSplit;
import doboard.signals.SignalDAO;
import javafx.application.Platform;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.stream.Collectors;

/**
 * Singleton in-memory cache for all dorm-scoped data.
 * Controllers read from here instead of hitting the DB on every tab switch.
 * Thread-safe: data is refreshed atomically, listeners fire on the FX thread.
 */
public class DormDataCache {

    private static DormDataCache instance;

    // --- CACHED DATA ---
    private volatile Dorm dorm;
    private volatile List<User> members = new ArrayList<>();
    private volatile List<Chore> chores = new ArrayList<>();
    private volatile List<Bill> bills = new ArrayList<>();
    private volatile Map<Integer, List<BillSplit>> billSplitsMap = new HashMap<>();
    private volatile List<SignalDAO.Signal> signals = new ArrayList<>();
    private volatile List<ChoreService.LeaderboardEntry> leaderboard = new ArrayList<>();
    private volatile int dormId = -1;
    private volatile int currentUserId = -1;

    // --- CHANGE DETECTION ---
    private volatile int lastDataHash = 0;

    // --- NOTIFICATION DIFFING ---
    // Snapshot of the PREVIOUS data state, used to compute diffs on each reload.
    private volatile DormNotificationDiffer.CacheSnapshot lastSnapshot = null;

    // --- LISTENER PATTERN ---
    private final CopyOnWriteArrayList<Runnable> onDataChangedListeners = new CopyOnWriteArrayList<>();

    // --- DAO REFERENCES ---
    private final DormDAO dormDAO = new DormDAO();
    private final ChoreDAO choreDAO = new ChoreDAO();
    private final ChoreService choreService = new ChoreService();
    private final BillDAO billDAO = new BillDAO();
    private final SignalDAO signalDAO = new SignalDAO();

    private DormDataCache() {}

    public static synchronized DormDataCache getInstance() {
        if (instance == null) {
            instance = new DormDataCache();
        }
        return instance;
    }

    // --- CORE RELOAD METHOD (called from background threads) ---

    /**
     * Result object returned by reload(). Carries both the changed flag and
     * a list of specific notification messages generated by the differ.
     * Groupmates can read notifications from here to display them anywhere.
     */
    public static class CacheReloadResult {
        public final boolean hasChanges;
        public final List<String> notifications;

        public CacheReloadResult(boolean hasChanges, List<String> notifications) {
            this.hasChanges = hasChanges;
            this.notifications = notifications;
        }
    }

    /**
     * Fetches ALL dorm-scoped data from the database in one shot.
     * This method is designed to be called from a background thread.
     *
     * @param dormId The dorm ID to load data for
     * @param userId The current user's ID (for signal filtering)
     * @return CacheReloadResult containing hasChanges flag + targeted notification strings
     */
    public CacheReloadResult reload(int dormId, int userId) {
        this.dormId = dormId;
        this.currentUserId = userId;

        if (dormId == -1) return new CacheReloadResult(false, new ArrayList<>());

        // 1. Fetch dorm info
        Dorm freshDorm = dormDAO.findById(dormId);

        // 2. Fetch members
        List<DormMember> dormMembers = dormDAO.getMembersByDorm(dormId);
        List<Integer> memberUserIds = dormMembers.stream()
                .map(DormMember::getUser_id)
                .collect(Collectors.toList());
        List<User> freshMembers = UserDAO.getUsersByIds(memberUserIds);

        // 3. Fetch chores
        List<Chore> freshChores = choreDAO.findAllByDormId(dormId);

        // 4. Fetch bills and their splits
        List<Bill> freshBills = billDAO.findBillByDormId(dormId);
        Map<Integer, List<BillSplit>> freshSplitsMap = new HashMap<>();
        for (Bill bill : freshBills) {
            freshSplitsMap.put(bill.getBill_id(), billDAO.findSplitsByBillId(bill.getBill_id()));
        }

        // 5. Fetch signals
        List<SignalDAO.Signal> freshSignals = signalDAO.getSignalsForUser(userId, dormId);

        // 6. Build leaderboard
        List<ChoreService.LeaderboardEntry> freshLeaderboard = choreService.getSortedLeaderboard(dormId);

        // 7. Compute hash to detect any change
        int newHash = computeHash(freshChores, freshBills, freshSplitsMap, freshSignals, freshMembers);
        boolean changed = (newHash != lastDataHash);

        // 8. Run notification differ BEFORE swapping — compares old snapshot to fresh data
        DormNotificationDiffer.CacheSnapshot freshSnapshot = new DormNotificationDiffer.CacheSnapshot(
                freshSignals, freshChores, freshBills, freshSplitsMap, userId);
        List<String> notifications = DormNotificationDiffer.computeDiffs(lastSnapshot, freshSnapshot);

        // 9. Atomically swap all cached data
        synchronized (this) {
            this.dorm = freshDorm;
            this.members = freshMembers;
            this.chores = freshChores;
            this.bills = freshBills;
            this.billSplitsMap = freshSplitsMap;
            this.signals = freshSignals;
            this.leaderboard = freshLeaderboard;
            this.lastDataHash = newHash;
            this.lastSnapshot = freshSnapshot; // Store for next comparison cycle
        }

        return new CacheReloadResult(changed, notifications);
    }

    /**
     * Fires all registered listeners on the JavaFX Application Thread.
     * Call this ONLY when changes have been detected.
     */
    public void notifyListeners() {
        Platform.runLater(() -> {
            for (Runnable listener : onDataChangedListeners) {
                try {
                    listener.run();
                } catch (Exception e) {
                    System.err.println("DormDataCache: Listener error: " + e.getMessage());
                }
            }
        });
    }

    // --- CHANGE DETECTION HASH ---
    private int computeHash(List<Chore> chores, List<Bill> bills,
                            Map<Integer, List<BillSplit>> splitsMap,
                            List<SignalDAO.Signal> signals, List<User> members) {
        int hash = 17;
        hash = 31 * hash + chores.size();
        hash = 31 * hash + bills.size();
        hash = 31 * hash + signals.size();
        hash = 31 * hash + members.size();

        // Include individual item states for finer detection
        for (Chore c : chores) {
            hash = 31 * hash + c.getChore_id();
            hash = 31 * hash + c.getStatus().ordinal();
        }
        for (Bill b : bills) {
            hash = 31 * hash + b.getBill_id();
        }
        for (Map.Entry<Integer, List<BillSplit>> entry : splitsMap.entrySet()) {
            for (BillSplit split : entry.getValue()) {
                hash = 31 * hash + split.getSplit_id();
                hash = 31 * hash + (split.isPaid() ? 1 : 0);
            }
        }
        for (SignalDAO.Signal s : signals) {
            hash = 31 * hash + s.id();
        }
        return hash;
    }

    // --- LISTENER MANAGEMENT ---

    public void addListener(Runnable listener) {
        onDataChangedListeners.add(listener);
    }

    public void removeListener(Runnable listener) {
        onDataChangedListeners.remove(listener);
    }

    public void clearListeners() {
        onDataChangedListeners.clear();
    }

    // --- THREAD-SAFE GETTERS ---

    public synchronized Dorm getDorm() { return dorm; }
    public synchronized List<User> getMembers() { return new ArrayList<>(members); }
    public synchronized List<Chore> getChores() { return new ArrayList<>(chores); }
    public synchronized List<Bill> getBills() { return new ArrayList<>(bills); }
    public synchronized List<BillSplit> getSplitsForBill(int billId) {
        List<BillSplit> splits = billSplitsMap.get(billId);
        return splits != null ? new ArrayList<>(splits) : new ArrayList<>();
    }
    public synchronized List<SignalDAO.Signal> getSignals() { return new ArrayList<>(signals); }
    public synchronized List<ChoreService.LeaderboardEntry> getLeaderboard() { return new ArrayList<>(leaderboard); }
    public int getDormId() { return dormId; }
    public int getCurrentUserId() { return currentUserId; }

    // --- RESET (called on logout) ---
    public synchronized void clear() {
        dorm = null;
        members = new ArrayList<>();
        chores = new ArrayList<>();
        bills = new ArrayList<>();
        billSplitsMap = new HashMap<>();
        signals = new ArrayList<>();
        leaderboard = new ArrayList<>();
        dormId = -1;
        currentUserId = -1;
        lastDataHash = 0;
        lastSnapshot = null; // Reset snapshot so next login starts fresh
        clearListeners();
    }
}
